# Server
server.port=8081

# App
spring.application.name=gv-welding-backend

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vasanthvasanth1945@gmail.com
spring.mail.password=ydwy tdmf tqve mowz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Business Mail
business.email.receiver=vasanthvasanth1945@gmail.com

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/weldingdb
spring.datasource.username=root
spring.datasource.password=Vasanth@33
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Logging
logging.level.com.gvwelding.api=INFO